version: '2.1'
#All Services in this stack communicate over the same Network, using a VPN-Service
services:
 transmission-openvpn: #Transmission deployment which utilizes a VPN-Connection
    volumes:
        - /data/downloads/openvpn:/data/completed
        - /etc/localtime:/etc/localtime:ro
        - /var/configs/vpnconf:/etc/openvpn/custom

    environment:
        - PUID=1000
        - PGID=1000
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=custom
        - OPENVPN_CONFIG=custom
        - OPENVPN_USERNAME=FHJaprvfxY
        - OPENVPN_PASSWORD=nSUNkK62Ef
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.188.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 8191:8191
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
        
    restart: always
    image: haugene/transmission-openvpn
 
 jackett: #Indexer for Torrent sites
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission-openvpn"
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /var/configs/jackett:/config
        - /data/downloads/jackett:/data
        #Jackett only needs config
    restart: unless-stopped

 flaresolverr: # Software emulates Browser to solve captchas
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:transmission-openvpn"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Berlin
    restart: unless-stopped

 radarr: #Manages literature
    image: linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - UMASK_SET=022 #optional
    volumes:
        - /data/downloads/openvpn:/data/completed
        - /var/configs/radarr:/config
        - /data/downloads/radarr:/media
    restart: unless-stopped
 
 sonarr: #Manages literature
    image: linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - UMASK_SET=022 #optional
    volumes:
        - /data/downloads/openvpn:/data/completed
        - /var/configs/sonarr:/config
        - /data/downloads/sonarr:/media
    restart: unless-stopped
 
 lidarr: #Manages literature
    image: linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: lidarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - UMASK_SET=022 #optional
    volumes:
        - /data/downloads/openvpn:/data/completed
        - /var/configs/lidarr:/config
        - /data/downloads/lidarr:/media
    restart: unless-stopped
 
 lazylibrarian: #Manages literature
    image: linuxserver/lazylibrarian
    network_mode: "service:transmission-openvpn"
    container_name: lazylibrarian
    environment:
        - PUID=1000
        - PGID=1000
         - TZ=Europe/Berlin
        #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional (Webreader for Ebooks basically)
    volumes:
        - /data/downloads/openvpn:/data/completed
        - /var/configs/lazylibrarian:/config
        - /data/downloads/lazylibrarian:/media
    restart: unless-stopped