version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-paper
    environment:
      EULA: "true"
      ENABLE_RCON: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 2G
      CONSOLE: "false"
    ports:
      - 25565:25565
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ssd2/minecraft:/data
    restart: unless-stopped
