version: "3.7"
services:
  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WG_HOST=<domain>
      - PASSWORD=<password>
    volumes:
      - /ssd2/wireguard:/etc/wireguard #Path mapping dependent on host system
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
